[features]
seeds = false
skip-lint = false

[programs.localnet]
synaptic = "SynapticProgram1111111111111111111111111"

[programs.devnet]
synaptic = "SynapticProgram1111111111111111111111111"

[programs.mainnet]
synaptic = "SynapticProgram1111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "SynaToken1111111111111111111111111111111"
program = "spl_token.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_token_metadata.so" 